# Generated by Django 4.1.4 on 2023-02-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Locality', models.CharField(max_length=50)),
                ('Description', models.TextField()),
            ],
        ),
    ]
